---
title: "Casos & Óbitos por COVID-19 na cidade de São Paulo"
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html'))})

output: html_document


---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=8, fig.height=4, fig.path='Figs/',
                      echo=FALSE, warning=FALSE, message=FALSE)
```



Gráficos montados a partir de dados que o https://brasil.io compila com base nos [boletins diários da Secretaria de Saúde do Município de São Paulo](https://www.prefeitura.sp.gov.br/cidade/secretarias/saude/vigilancia_em_saude/doencas_e_agravos/coronavirus/index.php?p=295572). 


Pontos para cada dia, assim como uma linha de tendência feita por ["amaciamento de médias"](https://ggplot2.tidyverse.org/reference/geom_smooth.html) (*Smoothed conditional means*).

```{r, limpando, echo=FALSE}
library(httr)
library(jsonlite)
library(dplyr)
library(tidyr)

# res = GET("https://brasil.io/api/dataset/covid19/caso_full/data/?search=&date=&state=&city=S%C3%A3o+Paulo&place_type=&is_last=&city_ibge_code=&order_for_place=")
# write.csv(dados_sp, "dados_sp_hj.csv")
# data = fromJSON(rawToChar(res$content))
# dados_sp = data[["results"]]


dados_sp = read.csv("dados_sp_hj.csv")


dados_sp_selecionada = dados_sp %>% select(c("date", "last_available_confirmed", "last_available_deaths", "order_for_place"))

colnames(dados_sp_selecionada) = c("Data", "Casos Confirmados Cumulativos", "Óbitos Confirmados Cumulativos", "Dia de contagem")
library(ggplot2)
library(plotly)


dados_sp_selecionada["Casos por dia"] <- c(-(diff(dados_sp_selecionada[,"Casos Confirmados Cumulativos"])),0)
dados_sp_selecionada["Óbitos Confirmados por dia"] <- c(-(diff(dados_sp_selecionada[,"Óbitos Confirmados Cumulativos"])),0)

dados_sp_selecionada_long = pivot_longer(dados_sp_selecionada, 
                                         cols = c("Casos Confirmados Cumulativos", "Óbitos Confirmados Cumulativos", "Casos por dia", "Óbitos Confirmados por dia"),
                                         names_to = "Tipo",
                                         values_to = "Contagem")


ultima_data = dados_sp_selecionada_long[["Data"]][1]
x_label = paste0('Contagem', " (até ", ultima_data, ")")

```

## Casos de COVID-19 por dia

```{r}
so_casos <- dados_sp_selecionada_long %>% filter(`Tipo` %in% c("Casos Confirmados Cumulativos", "Casos por dia"))

p1 = ggplot(so_casos, aes(x=`Dia de contagem`,
                          y = Contagem,
                          color = Tipo,
                          label = Data))    + 
  geom_point(size = 1) + 
  geom_smooth(size=2) +  
  ggtitle ("Casos confirmados de COVID-19 na cidade de São Paulo")+
  xlab(x_label)+ 
  labs(caption = "Fonte: Dados consolidados por Brasil IO a partir dos boletins da prefeitura ")

ggplotly(p1, tooltip = c("Contagem", "Data"))
```

```{r}
so_casos_por_dia <- dados_sp_selecionada_long %>% filter(`Tipo` %in% c("Casos por dia"))

p2 = ggplot(so_casos_por_dia, aes(x=`Dia de contagem`,
                          y = Contagem,
                          color = Tipo,
                          label = Data))    + 
  geom_point(size = 1) + 
  geom_smooth(size=2) +  
  ggtitle ("Casos confirmados de COVID-19 na cidade de São Paulo")+
  xlab(x_label)+ 
  labs(caption = "Fonte: Dados consolidados por Brasil IO a partir dos boletins da prefeitura ")

ggplotly(p2, tooltip = c("Contagem", "Data"))
```


## Óbitos por COVID-19 por dia

```{r}
so_obitos <- dados_sp_selecionada_long %>% filter(`Tipo` %in% c("Óbitos Confirmados Cumulativos", "Óbitos Confirmados por dia"))

p3 = ggplot(so_obitos, aes(x=`Dia de contagem`,
                          y = Contagem,
                          color = Tipo,
                          label = Data))    + 
  geom_point(size = 1) + 
  geom_smooth(size=2) + 
  ggtitle ("Óbitos confirmados de COVID-19 na cidade de São Paulo")+
  xlab(x_label)+ 
  labs(caption = "Fonte: Dados consolidados por Brasil IO a partir dos boletins da prefeitura ")

ggplotly(p3, tooltip = c("Contagem", "Data"))

```


```{r}
so_obitos_diarios <- dados_sp_selecionada_long %>% filter(`Tipo` %in% c("Óbitos Confirmados por dia"))
p4 = ggplot(so_obitos_diarios, aes(x=`Dia de contagem`,
                          y = Contagem,
                          color = Tipo,
                          label = Data))    + 
  geom_point(size = 1) + 
  geom_smooth(size=2) + 
  ggtitle ("Óbitos confirmados de COVID-19 na cidade de São Paulo")+
  xlab(x_label)+ 
  labs(caption = "Fonte: Dados consolidados por Brasil IO a partir dos boletins da prefeitura ")

ggplotly(p4, tooltip = c("Contagem", "Data"))
```


